### ISSUE TITLE
Only some to-dos displayed

### ISSUE THREAD

**Issue by o0nd7ots** [alphapapa/magit-todos#161] opened 2023-11-29 21:49 UTC
Hello!
I use `hl-todo` and `magit`, so I thought that I should try `magit-todos`.
I use the Elpaca package manager and my confg is:
```
 (use-package hl-todo
   :hook ((fundamental-mode . hl-todo-mode)
          (org-mode         . hl-todo-mode)
          (prog-mode        . hl-todo-mode)
          (text-mode        . hl-todo-mode))
   :config
   (setq 
    hl-todo-keyword-faces `(; #FBAe00
                            ("TODO"       highlight              bold)
                            ("WAIT"       font-lock-comment-face bold)
                            ("ERROR"      error                  extra-bold)
                            ("HACK"       font-lock-warning-face bold)
                            ("FIXME"      font-lock-type-face    bold)
                            ("REVIEW"     font-lock-keyword-face semi-bold)
                            ("NOTE"       success                bold)
                            ("DEPRECATED" font-lock-doc-face     normal)
                            )))
 (use-package flycheck-hl-todo
   :after flycheck
   :config (flycheck-hl-todo-setup))
 (use-package magit-todos
   ;; :after magit
   :config (magit-todos-mode 1))
```
I have commented out the `:after`, because I have run into some problems.

Basically, the `magit-todos-mode` is turned on and i DO have some files with *TODO* comments, but it shows nothing.
I think it should at least show the TODOs section, but it's not even the case:

![image](https://github.com/alphapapa/magit-todos/assets/124466962/26309e9f-ffed-4cdc-8d19-a6ea249a5368)
I think this a good example. There clearly are some TODOs on the `notes.org`, but I do not get anything at all.

I have tried reinstalling and unfortunately it stil does not work :<
When I do `magit-todos-jump-to-todos` I get the message `Section "TODOs" wasn’t found`.
`ivy-magit-todos` just prints `0    TODOS:   `

Does someone know how can I fix this?

**Comment by alphapapa** [comment] 2023-12-01 01:51
> Here you can see that it works.

Indeed, it works.

> As you can clearly see, it does not work:

What I see is that the `TODO` item in that file omits the colon suffix, whereas in the working example it has one.

If you don't want to use a colon suffix, you can customize the settings to make it optional.

**Comment by o0nd7ots** [comment] 2023-12-01 12:51
![image](https://github.com/alphapapa/magit-todos/assets/124466962/026a4b61-7cd7-4635-95db-dcaaf71b9811)
You are right!

Also in the screenshot you can see that punctuation that I customized to be highlighted (`!`) does not get pulled into the screen.

I did not expect this behaviour at all.
The default config for hl-todo is _not_ to highlight punctuation. This gives the impression that `hl-todo-mode` and `magit-todos` are not supposed to be tightly integrated, and I thought that it is so. Did I get it wrong?

**Comment by alphapapa** [comment] 2023-12-01 23:33
> I did not expect this behaviour at all. The default config for hl-todo is _not_ to highlight punctuation. This gives the impression that `hl-todo-mode` and `magit-todos` are not supposed to be tightly integrated, and I thought that it is so. Did I get it wrong?

I guess you misunderstood.  They are not intended to be tightly integrated.  This package can use the `hl-todo` keywords as a convenience, nothing more.  They are separate packages and separate tools.  (Maybe I should remove that integration, as it seems to confuse users.)

> do you think it would be a good idea to expand default `magit-todos-keyword-suffix` to include user-defined `hl-todo-highlight-punctuation`?

No, I think that would make it more complicated and confusing for users--and especially for me, having to deal with reports about interactions between separate packages.

But if you have code in your config that syncs some of their options, well, that's the power of Emacs.  But please be careful not to report a false bug if that code doesn't always work as intended; neither I nor the `hl-todo` maintainer have anything to do with your code, and we are not coordinating on these packages.

> Also I noticed that the program requires ':' at the end of the expression. Could you please explain what is the reasoning behind that?

It's a common pattern, and it helps distinguish words that might appear similar to a configured keyword but not be intended as one.  For example, consider `;; HACK: I should get rid of this someday` and `;; HACK THESE LOCAL VARIABLES!`: the first is intended as a to-do item, while the second is just a comment.  Yet, being a customization option, you can configure it however you like, even per-project with dir-local variables.

> Actually, this is false. If you look closely to the listing, you will see that I have both TODO and TODO: there.

It's not false; I saw both of them.  But your screenshot doesn't appear to be in sync with the text you pasted later.  And the lack of a colon likely explains why one of them is missing.

I can't see any bug here, so I'm closing this report.  I've handled many reports similar to this one over the years, and they almost always turn out to be misunderstandings or configuration problems.  You can see that properly formatted items are indeed displayed correctly.

If you still think there is a bug, you'll need to develop a minimal working example that reproduces the problem in a clean Emacs configuration and a tiny git repo that serves just to illustrate the problem.  Otherwise there are too many variables at play to allow isolating a cause.  Thanks.

**Closed by alphapapa** 2023-12-01 23:33 UTC

**Comment by jackmac92** [comment] 2024-09-21 01:48
> What I see is that the `TODO` item in that file omits the colon suffix, whereas in the working example it has one.

finally found my issue was the same as above after a bit of searching, I think highlighting the role of `magit-todos-keyword-suffix` in the README would help others figure out the same a bit more quickly

**Comment by alphapapa** [comment] 2024-09-21 10:43
@jackmac92 Thanks for the suggestion.  Please see https://github.com/alphapapa/magit-todos/commit/4a5a8b1a7156bc9a04a8072884b82337c537c0cd and let me know if you think that's helpful.

**Comment by jackmac92** [comment] 2024-09-21 21:11
@alphapapa yea that looks great
