### ISSUE TITLE
no todos in magit-status-buffer

### ISSUE THREAD

**Issue by phisu** [alphapapa/magit-todos#117] opened 2021-04-25 08:24 UTC
i am using the newest centaur configuration framework on emacs 27.2 (ubuntu 20.10) a fresh installation from yesterday.

i am unable to get magit-todos-mode to run.  when i call magit-status, i do not see todos of my project. but in the minibuffer i get the message 

`magit-todos: Not overriding bind of "jT" in ‘magit-status-mode-map’.`

when i am in the magit-status-buffer 'j-T' does not exists. so i try M-x magit-todos-jump-to-todos. but i get only "Section "TODOs" wasn't found.

I no longer know my way around and i did not found any helpful hints by googling this issue.

can you help me to get magit-todos running?

I asked the same question the maintainer of the centauer framework. I quote his answer here: 

https://github.com/seagle0128/.emacs.d/issues/301#issuecomment-826120275

**Comment by 7ym0n** [comment] 2021-05-20 05:15
I have the same problem. It was OK some time ago. After restarting Emacs, it won't be displayed, and the configuration hasn't changed

**Comment by alphapapa** [comment] 2021-06-03 21:08
I am unable to reproduce any problem in a clean Emacs configuration (i.e. everything works).  I can't help you with specialized configs like Centaur.

Since there seems to be no bug in this package, I'm closing this issue.  If you can reproduce a problem in a clean config, please let me know.

@seagle0128

**Closed by alphapapa** 2021-06-03 21:08 UTC

**Comment by seagle0128** [comment] 2021-06-04 05:09
I reproduced this issue with `emacs -Q` on macOS (gccemacs 28).

I think @phisu @7ym0n can provide more details.

**Comment by alphapapa** [comment] 2021-06-04 10:32
I can't offer support for MacOS, and Emacs 28 is yet to be released (won't be for at least another year), so I'm not very inclined to work on bugs specific to it.  If the package doesn't function properly on the latest released version of Emacs on a free platform like GNU/Linux, maybe there's a bug to be fixed caused by a change in Emacs or Magit, but that seems unlikely, especially since I tested with the latest version of Magit.

**Comment by phisu** [comment] 2021-06-04 12:15
this helped: https://github.com/seagle0128/.emacs.d/issues/301#issuecomment-853915977

**Comment by alphapapa** [comment] 2021-06-08 01:15
@phisu IIUC, you are confirming that your to-do items were not in the correct format, and that there is no bug in this package, correct?

**Comment by phisu** [comment] 2021-06-08 05:29
yes, my to-do items were not in the correct format. sorry for the inconenience.
