### ISSUE TITLE
TODO menu lost colors?

### ISSUE THREAD

**Issue by GLodi** [alphapapa/magit-todos#84] opened 2019-08-22 21:05 UTC
![todocolors](https://user-images.githubusercontent.com/4631114/63549610-0a656f80-c531-11e9-8bf2-2ce8ddd57ae9.png)

I've noticed that suddenly the TODO menu has lost all its colors. I've searched in magit's customize_group, but nothing seems out of order.

Any idea on how to get them back?

Thanks.

**Comment by muihlinn** [comment] 2019-08-22 21:56
Only as note, When status is refreshed there are colors, but they go away as soon as refresh is done.

**Comment by alphapapa** [comment] 2019-08-23 00:15
That's a very strange problem.  Please try to reproduce by running `emacs -q` and loading the necessary packages.  If you can't reproduce it, it must be a problem with your Emacs config.  If you can reproduce it, you'll need to provide more information, because a screenshot is not enough for me to go on.

**Comment by alphapapa** [comment] 2019-08-23 00:17
Well, I tested in the MELPA sandbox, and I see the same problem.  Magit must have made an incompatible change...sigh...

**Comment by alphapapa** [comment] 2019-08-23 00:43
Thanks for reporting this.  We'll see what Magit decides to do...

**Comment by alphapapa** [comment] 2019-08-23 06:08
@muihlinn Noam Postavsky was kind enough to fix the problem very quickly.  I've verified that it's fixed by testing in the MELPA sandbox.  Thanks for reporting this quickly!

**Closed by alphapapa** 2019-08-23 06:08 UTC
Labels: WAITING, bug, upstream
